name: lkarnet

description: A new Flutter project.

publish_to: "none"

version: 1.0.1+311

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  awesome_notifications: ^0.7.4+1
  bottom_navy_bar: ^6.0.0
  cloud_firestore: ^4.5.2
  cupertino_icons: ^1.0.2
  firebase_app_check: ^0.1.2+2
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.3.6
  flutter_slidable: ^2.0.0
  flutter_svg: ^2.0.5
  flutter_typeahead: ^4.0.0
  google_fonts: ^4.0.3
  #google_sign_in: ^5.2.3
  logger: ^1.1.0
  percent_indicator: ^4.2.2
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.15
  syncfusion_flutter_charts: ^21.1.41
  syncfusion_flutter_gauges: ^21.1.41
  workmanager: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
