name: lkarnet

description: A new Flutter project.

publish_to: "none"

version: 1.0.1+311

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  awesome_notifications: ^0.6.21
  bloc: ^8.0.3
  bottom_navy_bar: ^6.0.0
  cloud_firestore: ^3.1.18
  cloud_functions: ^3.2.17
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_app_check: ^0.0.6+12
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  firebase_messaging: ^11.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^1.0.4
  flutter_slidable: ^1.2.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  flutter_typeahead: ^4.0.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  overlay_support: ^2.0.1
  package_info_plus: ^1.4.2
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  permission_handler: ^10.0.0
  shared_preferences: ^2.0.15
  syncfusion_flutter_charts: ^20.1.56
  syncfusion_flutter_gauges: ^20.1.56
  url_launcher: ^6.1.4
  workmanager: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
