name: lkarnet

description: A new Flutter project.

publish_to: "none"

version: 2.0.4+204

environment:
  sdk: ">=2.12.0-259.12.beta <3.0.0"

dependencies:
  bottom_navy_bar: ^6.0.0
  cloud_firestore: ^3.1.6
  cupertino_icons: ^1.0.2
  #downloads_path_provider_28: ^0.1.2
  equatable: ^2.0.0
  firebase_app_check: ^0.0.6+4
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  fl_chart: ^0.41.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  flutter_slidable: ^1.2.0
  flutter_svg: ^1.0.1
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.3
  logger: ^1.1.0
  #path_provider: ^2.0.8
  percent_indicator: ^3.4.0
  permission_handler: ^8.3.0
  shared_preferences: ^2.0.12
  syncfusion_flutter_charts: ^19.4.42

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
